on: [push]

jobs:
  hello_world_job:
    runs-on: windows-latest
    name: A job to say hello
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'az login'
        uses: ./ # Uses an action in the root directory
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"